export const FETCH_IMAGES_API_CALL = 'FETCH_IMAGES_API_CALL';
export const FETCH_IMAGES_API_SUCCESS = 'FETCH_IMAGE_API_SUCCESS';
export const FETCH_IMAGES_API_ERROR = 'FETCH_IMAGE_API_ERROR';
export const CHANGE_GRID_COLUMN_NO = 'CHANGE_GRID_COLUMN_NO';
